# Generated by Django 5.2 on 2026-02-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='league_covers/'),
        ),
    ]
