# Generated by Django 5.2 on 2026-02-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_post_comment_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event',
        ),
        migrations.AddField(
            model_name='post',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.league'),
        ),
    ]
