# Generated by Django 5.2 on 2026-02-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_post_event_post_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
