# Generated by Django 5.2 on 2026-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
