# Generated by Django 6.0.4 on 2026-04-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_league_cover_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
