# Generated by Django 6.0.4 on 2026-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reschedule', 'Event Rescheduled'), ('cancel', 'Event Cancelled'), ('new_event', 'New Event'), ('message', 'New Message'), ('invite', 'Invited')], max_length=20),
        ),
    ]
