# Generated by Django 6.0.4 on 2026-08-16 13:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_poll_pollchoice_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=api.models.generate_verification_code, max_length=6, unique=True),
        ),
    ]
