# Generated by Django 6.0.4 on 2026-08-24 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_emailverificationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_invite_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reschedule', 'Event Rescheduled'), ('cancel', 'Event Cancelled'), ('new_event', 'New Event'), ('message', 'New Message'), ('invite', 'Invited'), ('join_request', 'Join Request'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('activity', 'user')},
            },
        ),
    ]
