# Generated by Django 6.0.4 on 2026-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_activity_is_invite_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reschedule', 'Event Rescheduled'), ('cancel', 'Event Cancelled'), ('new_event', 'New Event'), ('message', 'New Message'), ('invite', 'Invited'), ('join_request', 'Join Request'), ('request_accepted', 'Request Accepted'), ('request_declined', 'Request Declined'), ('content_flagged', 'Content Flagged')], max_length=20),
        ),
    ]
